# Generated by Django 5.2.5 on 2025-09-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_tag_alter_task_options_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', '-priority', 'due_date', '-created_at']},
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
